ros2_template_pkg: MinimalActionClient Class Reference
MinimalActionClient Class Reference
Public Types
using Fibonacci = acfr_ros2_interfaces::action::Fibonacci
using GoalHandleFibonacci = rclcpp_action::ClientGoalHandle< Fibonacci >
Public Member Functions
MinimalActionClient (const rclcpp::NodeOptions &node_options=rclcpp::NodeOptions())
bool is_goal_done () const
void send_goal ()
Private Member Functions
void goal_response_callback (GoalHandleFibonacci::SharedPtr goal_handle)
void feedback_callback (GoalHandleFibonacci::SharedPtr, const std::shared_ptr< const Fibonacci::Feedback > feedback)
void result_callback (const GoalHandleFibonacci::WrappedResult &result)
Private Attributes
rclcpp_action::Client< Fibonacci >::SharedPtr client_ptr_
rclcpp::TimerBase::SharedPtr timer_
bool goal_done_
Detailed Description
Definition at line 12 of file fibonaaci_action_client_node.cpp.
Member Typedef Documentation
Fibonacci
using MinimalActionClient::Fibonacci = acfr_ros2_interfaces::action::Fibonacci
Definition at line 15 of file fibonaaci_action_client_node.cpp.
GoalHandleFibonacci
using MinimalActionClient::GoalHandleFibonacci = rclcpp_action::ClientGoalHandle<Fibonacci>
Definition at line 16 of file fibonaaci_action_client_node.cpp.
Constructor & Destructor Documentation
MinimalActionClient()
MinimalActionClient::MinimalActionClient (const rclcpp::NodeOptions & node_options = rclcpp::NodeOptions()) inline explicit
Definition at line 18 of file fibonaaci_action_client_node.cpp.
   : Node("minimal_action_client", node_options), goal_done_(false)
   {
     this->client_ptr_ = rclcpp_action::create_client<Fibonacci>(
       this->get_node_base_interface(),
       this->get_node_graph_interface(),
       this->get_node_logging_interface(),
       this->get_node_waitables_interface(),
       "fibonacci");
     this->timer_ = this->create_wall_timer(
       std::chrono::milliseconds(500),
       std::bind(&MinimalActionClient::send_goal, this));
   }
References client_ptr_, send_goal(), and timer_.
Member Function Documentation
feedback_callback()
void MinimalActionClient::feedback_callback (GoalHandleFibonacci::SharedPtr , const std::shared_ptr< const Fibonacci::Feedback > feedback) inline private
Definition at line 85 of file fibonaaci_action_client_node.cpp.
   {
     RCLCPP_INFO(
       this->get_logger(),
       "Next number in sequence received: %" PRId32,
       feedback->sequence.back());
   }
Referenced by send_goal().
goal_response_callback()
void MinimalActionClient::goal_response_callback (GoalHandleFibonacci::SharedPtr goal_handle) inline private
Definition at line 76 of file fibonaaci_action_client_node.cpp.
   {
     if (!goal_handle) {
       RCLCPP_ERROR(this->get_logger(), "Goal was rejected by server");
     } else {
       RCLCPP_INFO(this->get_logger(), "Goal accepted by server, waiting for result");
     }
   }
Referenced by send_goal().
is_goal_done()
bool MinimalActionClient::is_goal_done () const inline
Definition at line 33 of file fibonaaci_action_client_node.cpp.
   {
     return this->goal_done_;
   }
References goal_done_.
result_callback()
void MinimalActionClient::result_callback (const GoalHandleFibonacci::WrappedResult & result) inline private
Definition at line 95 of file fibonaaci_action_client_node.cpp.
   {
     this->goal_done_ = true;
     switch (result.code) {
       case rclcpp_action::ResultCode::SUCCEEDED:
         break;
       case rclcpp_action::ResultCode::ABORTED:
         RCLCPP_ERROR(this->get_logger(), "Goal was aborted");
         return;
       case rclcpp_action::ResultCode::CANCELED:
         RCLCPP_ERROR(this->get_logger(), "Goal was canceled");
         return;
       default:
         RCLCPP_ERROR(this->get_logger(), "Unknown result code");
         return;
     }
     RCLCPP_INFO(this->get_logger(), "Result received");
     for (auto number : result.result->sequence) {
       RCLCPP_INFO(this->get_logger(), "%" PRId32, number);
     }
   }
Referenced by send_goal().
send_goal()
void MinimalActionClient::send_goal () inline
Definition at line 38 of file fibonaaci_action_client_node.cpp.
   {
     using namespace std::placeholders;
     this->timer_->cancel();
     this->goal_done_ = false;
     if (!this->client_ptr_) {
       RCLCPP_ERROR(this->get_logger(), "Action client not initialized");
     }
     if (!this->client_ptr_->wait_for_action_server(std::chrono::seconds(10))) {
       RCLCPP_ERROR(this->get_logger(), "Action server not available after waiting");
       this->goal_done_ = true;
       return;
     }
     auto goal_msg = Fibonacci::Goal();
     goal_msg.order = 10;
     RCLCPP_INFO(this->get_logger(), "Sending goal");
     auto send_goal_options = rclcpp_action::Client<Fibonacci>::SendGoalOptions();
     send_goal_options.goal_response_callback =
       std::bind(&MinimalActionClient::goal_response_callback, this, _1);
     send_goal_options.feedback_callback =
       std::bind(&MinimalActionClient::feedback_callback, this, _1, _2);
     send_goal_options.result_callback =
       std::bind(&MinimalActionClient::result_callback, this, _1);
     auto goal_handle_future = this->client_ptr_->async_send_goal(goal_msg, send_goal_options);
   }
References client_ptr_, feedback_callback(), goal_done_, goal_response_callback(), result_callback(), and timer_.
Referenced by MinimalActionClient().
Member Data Documentation
client_ptr_
rclcpp_action::Client<Fibonacci>::SharedPtr MinimalActionClient::client_ptr_ private
Definition at line 72 of file fibonaaci_action_client_node.cpp.
Referenced by MinimalActionClient(), and send_goal().
goal_done_
bool MinimalActionClient::goal_done_ private
Definition at line 74 of file fibonaaci_action_client_node.cpp.
Referenced by is_goal_done(), and send_goal().
timer_
rclcpp::TimerBase::SharedPtr MinimalActionClient::timer_ private
Definition at line 73 of file fibonaaci_action_client_node.cpp.
Referenced by MinimalActionClient(), and send_goal().
The documentation for this class was generated from the following file:
src/fibonaaci_action_client_node.cpp