ros2_template_pkg: MinimalActionServer Class Reference
MinimalActionServer Class Reference
Public Types
using Fibonacci = acfr_ros2_interfaces::action::Fibonacci
using GoalHandleFibonacci = rclcpp_action::ServerGoalHandle< Fibonacci >
Public Member Functions
MinimalActionServer (const rclcpp::NodeOptions &options=rclcpp::NodeOptions())
Private Member Functions
rclcpp_action::GoalResponse handle_goal (const rclcpp_action::GoalUUID &uuid, std::shared_ptr< const Fibonacci::Goal > goal)
rclcpp_action::CancelResponse handle_cancel (const std::shared_ptr< GoalHandleFibonacci > goal_handle)
void execute (const std::shared_ptr< GoalHandleFibonacci > goal_handle)
void handle_accepted (const std::shared_ptr< GoalHandleFibonacci > goal_handle)
Private Attributes
rclcpp_action::Server< Fibonacci >::SharedPtr action_server_
Detailed Description
Definition at line 38 of file fibonaaci_action_server_node.cpp.
Member Typedef Documentation
Fibonacci
using MinimalActionServer::Fibonacci = acfr_ros2_interfaces::action::Fibonacci
Definition at line 41 of file fibonaaci_action_server_node.cpp.
GoalHandleFibonacci
using MinimalActionServer::GoalHandleFibonacci = rclcpp_action::ServerGoalHandle<Fibonacci>
Definition at line 42 of file fibonaaci_action_server_node.cpp.
Constructor & Destructor Documentation
MinimalActionServer()
MinimalActionServer::MinimalActionServer (const rclcpp::NodeOptions & options = rclcpp::NodeOptions()) inline explicit
Definition at line 44 of file fibonaaci_action_server_node.cpp.
   : Node("minimal_action_server", options)
   {
     using namespace std::placeholders;
     this->action_server_ = rclcpp_action::create_server<Fibonacci>(
       this->get_node_base_interface(),
       this->get_node_clock_interface(),
       this->get_node_logging_interface(),
       this->get_node_waitables_interface(),
       "fibonacci",
       std::bind(&MinimalActionServer::handle_goal, this, _1, _2),
       std::bind(&MinimalActionServer::handle_cancel, this, _1),
       std::bind(&MinimalActionServer::handle_accepted, this, _1));
   }
References action_server_, handle_accepted(), handle_cancel(), and handle_goal().
Member Function Documentation
execute()
void MinimalActionServer::execute (const std::shared_ptr< GoalHandleFibonacci > goal_handle) inline private
Definition at line 84 of file fibonaaci_action_server_node.cpp.
   {
     RCLCPP_INFO(this->get_logger(), "Executing goal");
     rclcpp::Rate loop_rate(1);
     const auto goal = goal_handle->get_goal();
     auto feedback = std::make_shared<Fibonacci::Feedback>();
     auto & sequence = feedback->sequence;
     sequence.push_back(0);
     sequence.push_back(1);
     auto result = std::make_shared<Fibonacci::Result>();
     for (int i = 1; (i < goal->order) && rclcpp::ok(); ++i) {
       // Check if there is a cancel request
       if (goal_handle->is_canceling()) {
         result->sequence = sequence;
         goal_handle->canceled(result);
         RCLCPP_INFO(this->get_logger(), "Goal Canceled");
         return;
       }
       // Update sequence
       sequence.push_back(sequence[i] + sequence[i - 1]);
       // Publish feedback
       goal_handle->publish_feedback(feedback);
       RCLCPP_INFO(this->get_logger(), "Publish Feedback");
       loop_rate.sleep();
     }
     // Check if goal is done
     if (rclcpp::ok()) {
       result->sequence = sequence;
       goal_handle->succeed(result);
       RCLCPP_INFO(this->get_logger(), "Goal Succeeded");
     }
   }
Referenced by handle_accepted().
handle_accepted()
void MinimalActionServer::handle_accepted (const std::shared_ptr< GoalHandleFibonacci > goal_handle) inline private
Definition at line 120 of file fibonaaci_action_server_node.cpp.
   {
     using namespace std::placeholders;
     // this needs to return quickly to avoid blocking the executor, so spin up a new thread
     std::thread{std::bind(&MinimalActionServer::execute, this, _1), goal_handle}.detach();
   }
References execute().
Referenced by MinimalActionServer().
handle_cancel()
rclcpp_action::CancelResponse MinimalActionServer::handle_cancel (const std::shared_ptr< GoalHandleFibonacci > goal_handle) inline private
Definition at line 76 of file fibonaaci_action_server_node.cpp.
   {
     RCLCPP_INFO(this->get_logger(), "Received request to cancel goal");
     (void)goal_handle;
     return rclcpp_action::CancelResponse::ACCEPT;
   }
Referenced by MinimalActionServer().
handle_goal()
rclcpp_action::GoalResponse MinimalActionServer::handle_goal (const rclcpp_action::GoalUUID & uuid, std::shared_ptr< const Fibonacci::Goal > goal) inline private
Definition at line 63 of file fibonaaci_action_server_node.cpp.
   {
     RCLCPP_INFO(this->get_logger(), "Received goal request with order %d", goal->order);
     (void)uuid;
     // Let's reject sequences that are over 9000
     if (goal->order > 9000) {
       return rclcpp_action::GoalResponse::REJECT;
     }
     return rclcpp_action::GoalResponse::ACCEPT_AND_EXECUTE;
   }
Referenced by MinimalActionServer().
Member Data Documentation
action_server_
rclcpp_action::Server<Fibonacci>::SharedPtr MinimalActionServer::action_server_ private
Definition at line 61 of file fibonaaci_action_server_node.cpp.
Referenced by MinimalActionServer().
The documentation for this class was generated from the following file:
src/fibonaaci_action_server_node.cpp