name: Test Template

on:
  pull_request:
  push:
    branches:
      - ament_lint
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: humble
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        target-ros2-distro: humble
        package-name: ros2_template_pkg
    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()