name: Test Template

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_docker:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.3
        with:
          required-ros-distributions: humble
      - name: Run Tests
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          target-ros2-distro: humble
          package-name: ros2_template_pkg
      - name: Upload Logs
        uses: actions/upload-artifact@v1
        with:
          name: colcon-logs
          path: ros_ws/log
        if: always()
